# Generated by Django 6.0.4 on 2026-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_codigopostal'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cedula',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
