# Generated by Django 6.0.4 on 2026-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paciente_medico_asignado_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
