# Generated by Django 6.0.4 on 2026-05-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='core.paciente')),
            ],
        ),
    ]
