# Generated by Django 6.0.4 on 2026-05-13 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EMG', 'Emergencia Manual'), ('FC', 'Frecuencia Cardíaca'), ('SpO2', 'Saturación Oxígeno'), ('PA', 'Presión Arterial'), ('Temp', 'Temperatura')], max_length=10)),
                ('message', models.TextField()),
                ('value', models.CharField(max_length=50)),
                ('resuelto', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.paciente')),
            ],
        ),
    ]
