# Generated by Django 6.0.4 on 2026-05-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='recetas_pdf/'),
        ),
    ]
